### ISSUE TITLE
Cannot find type 'CGFloat' in scope

### ISSUE THREAD

**Issue by scriptprojectsdev** [marshallino16/ImageCropper#1]
I'm using Xcode 12.5 and I'm getting the following error in the `CropperRatio.swift`
`Cannot find type 'CGFloat' in scope` 
I think this can be fixed by adding `import CoreGraphics` to that file

**Comment by scriptprojectsdev** [comment]
I created a pull request that fixes this issue here [https://github.com/marshallino16/ImageCropper/pull/2](https://github.com/marshallino16/ImageCropper/pull/2)

**Comment by marshallino16** [comment]
Thank you!
